version: '3.8'

services:
  webapp:
    build: .  # Builds from the current directory where Dockerfile is located
    ports:
      - "3000:3000"  # Exposes the web app on port 3000
    container_name: webapp-container
    environment:
      - MYSQL_URL=mysql://webapp_user:webapp_password@database/animals
    depends_on:
      - database  # Ensures that the MySQL database starts before the web app
    restart: always  # Automatically restarts the container if it stops

  database:
    image: mysql:8.0  # Official MySQL 8.0 image
    container_name: mysql-database
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # Root password for MySQL
      MYSQL_DATABASE: animals  # The database that the app will use
      MYSQL_USER: webapp_user  # User created for the web app
      MYSQL_PASSWORD: webapp_password  # Password for the web app user
    ports:
      - "3306:3306"  # Exposes MySQL (optional, remove if you don't need external access)
    restart: always  # Automatically restarts the container if it stops

  test:
    build: .  # Use the webapp Dockerfile to build the image for the tests
    container_name: test-container
    environment:
      - API_URL=http://webapp:3000  # URL of the web app service
    depends_on:
      - webapp
      - database  # Ensure webapp and database are started before running tests
    command: yarn test  # Override the default command with 'yarn test'

# No external volumes
