name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Run linting
        run: yarn lint

      # New Step to Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # Using repo secret for Docker Hub username
          password: ${{ secrets.DOCKERHUB_PASSWORD }}  # Using repo secret for Docker Hub password

      # Updated Step to Build and Push Docker Image
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .                     # Use the root directory as the context
          file: ./Dockerfile             # Path to your Dockerfile
          tags: your-docker-hub-username/webapp:latest # Replace with your Docker Hub username
          push: true                     # Push the image to Docker Hub
