name: Build, run, and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Run linting
        run: yarn lint

      - name: Set up Docker Buildx (includes Docker Compose)
        uses: docker/setup-buildx-action@v2
        with:
          install: true  # Ensure Docker Buildx and Docker Compose are installed

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .                     # Use the root directory as the context
          file: ./dockerfile             # Path to your Dockerfile
          tags: mmeheus/webapp:latest 
          push: true                     # Push the image to Docker Hub

      # Use Docker Compose Action to manage Docker services
      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"

      # Optional: Wait for services to be ready (use sleep or other health checks as needed)
      - name: Wait for services to be ready
        run: sleep 30  # Adjust wait time if necessary

      # Run tests using `yarn test` after containers are up
      - name: Run tests
        run: yarn test

      - name: Check for vulnerabilities with Snyk
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Snyk test
        run: snyk test
