name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4 

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Run linting
        run: yarn lint

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      #Step to Build and Push Docker Image
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .                     # Use the root directory as the context
          file: ./dockerfile             # Path to your Dockerfile
          tags: mmeheus/webapp:latest 
          push: true                     # Push the image to Docker Hub

      - name: Check for vulnerabilities with Snyk
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
            
      - name: Snyk test
        run: snyk test